# Generated by Django 3.2.16 on 2023-12-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231221_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='api.post'),
        ),
    ]
